### ISSUE TITLE
world sbk 2024 first event from ics file doesn't load into google calendar

### ISSUE THREAD

**Issue by EmanueleCannizzaro** [nixxo/motorsport-calendar-creator#1]
world sbk 2024 first event from ics file doesn't load into google calendar

**Comment by nixxo** [comment]
![Screenshot_20240222-221351](https://github.com/nixxo/motorsport-calendar-creator/assets/426049/7624bbe2-c3df-477e-b079-4e9f6d4f353c)
![Screenshot_20240222-220954](https://github.com/nixxo/motorsport-calendar-creator/assets/426049/3649088f-b8b9-43ef-9dd4-f6be24396618)

**Comment by nixxo** [comment]
I've tried importing from a downloaded ics file or subscribing directly to the calendar url and both works ok for me.

Can you provide extra info on your situstion?

**Comment by EmanueleCannizzaro** [comment]
Hello,

Do you seen the event this week end in Google calendar?

I do not.

I see the next one but not the first weekend.

Thank you

**Comment by EmanueleCannizzaro** [comment]
Sorry my fault.
The issue was that the event in Australia is during the night in Italy and
the calendar was showing only daytime.

Cheers.

**Comment by nixxo** [comment]
Yes, you can see it in the screenshot I posted.

**Comment by EmanueleCannizzaro** [comment]
Thank you for making the calendars available.

**Comment by nixxo** [comment]
hai poi risolto? che problema c'era?
